### ISSUE TITLE
Documentation: Windows MSI builds

### ISSUE THREAD

**Issue by rmc3** [sensu/sensu-build#102]
This project appears to build the Windows MSIs, because Wix assets are available and there are several platform-specific switches in the code for Windows. Unfortunately, the ```Vagrantfile``` doesn't describe any Windows boxes, and a vanilla Windows VM can't run ```build.sh``` without a supporting *nix-like environment.

Is there any existing documentation available on how to do so? Either way, it would be very helpful to have documentation on the process for Windows MSI builds documented in the README.

**Comment by amdprophet** [comment]
This will be fixed by https://github.com/sensu/sensu-omnibus/issues/31.
