### ISSUE TITLE
Windows v0.17.0.beta missing sensu-client

### ISSUE THREAD

**Issue by cloakedcode** [sensu/sensu-build#105]
I've been trying out the windows v0.17.0.beta build, however, it doesn't seem to install C:\opt\sensu\embedded\bin\sensu-client even though that's where C:\opt\sensu\bin\sensu-client.xml expects to find the script.

I've uninstalled sensu and reinstalled, rather than an upgrade, to no avail.

Am I missing something?

**Comment by portertech** [comment]
The CI job was using `bundle exec`, which interferred w/ the embedded gem install process. A replacement MSI is on the way!

**Comment by portertech** [comment]
The 0.17.0.beta-1 MSI has been replaced by the build w/o `bundle exec`.

**Comment by cloakedcode** [comment]
I have downloaded the v0.17.0.beta-1 build but it has the same issue. Was the replacement uploaded? That's the only 17 build.

**Comment by portertech** [comment]
@cloakedcode I'll purge the CDN and see if that does it.

**Comment by portertech** [comment]
Ah, didn't sync the replacement to S3 from the CI box.

**Comment by portertech** [comment]
@cloakedcode OK, synced and CDN purged.

**Comment by cloakedcode** [comment]
That did it.
