### ISSUE TITLE
EMBEDDED_RUBY is not evaluated in systemd scripts

### ISSUE THREAD

**Issue by Debilski** [sensu/sensu-build#108]
In the systemd scripts even when adding a setting `EnvironmentFile=/etc/defaults/sensu`, the environment variable `EMBEDDED_RUBY` is never checked.

**Comment by jhmartin** [comment]
On a CentOS7 machine, having modified sensu-ctl to know to use systemd, I have:
```
$ cat /etc/default/sensu
EMBEDDED_RUBY=true
```

and

```
$ ps -ef|grep sensu
root     26182     1  0 14:44 ?        00:00:00 /opt/sensu/embedded/bin/runsvdir -P /opt/sensu/service log: .................................................................................................................................
root     26197 26182  0 14:44 ?        00:00:00 runsv sensu-client
sensu    26381 26197  0 14:45 ?        00:00:00 /opt/sensu/embedded/bin/ruby /opt/sensu/bin/sensu-client -c /etc/sensu/config.json -d /etc/sensu/conf.d -e /etc/sensu/extensions -l /var/log/sensu/sensu-client.log
````

It seems to be honoring the embedded ruby.

**Comment by Debilski** [comment]
I am mainly on Debian 8:

    $ ps -ef | grep sensu
    sensu     2591     1  0 17:00 ?        00:00:01 /opt/sensu/embedded/bin/ruby /opt/sensu/bin/sensu-client -c /etc/sensu/config.json -d /etc/sensu/conf.d -e /etc/sensu/extensions -l /var/log/sensu/sensu-client.log

    $ systemctl cat sensu-client.service 
    # /etc/systemd/system/sensu-client.service
    [Unit]
    Description=sensu client
    [Service]
    User=sensu
    Group=sensu
    ExecStart=/opt/sensu/bin/sensu-client -c /etc/sensu/config.json -d /etc/sensu/conf.d -e /etc/sensu/extensions -l /var/log/sensu
    KillMode=process
    Restart=on-failure
    RestartSec=1min
    EnvironmentFile=/etc/default/sensu
    [Install]
    WantedBy=multi-user.target

And yet when I run, say, `/opt/sensu-plugins/sensu-community-plugins/plugins/system/memory-metrics.rb` from the community plugins I get:

    /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sensu-plugin/metric/cli (LoadError) from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require' from /opt/sensu-plugins/sensu-community-plugins/plugins/system/memory-metrics.rb:28:in `<main>'

I could solve the problem by having my own `EnvironmentFile`:

    $ cat /etc/default/sensu.puppet 
    EXTENSION_DIR=/etc/sensu/extensions
    PLUGINS_DIR=/etc/sensu/plugins
    HANDLERS_DIR=/etc/sensu/handlers
    PATH=/opt/sensu/embedded/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/etc/sensu/plugins:/etc/sensu/handlers
    GEM_PATH=/opt/sensu/embedded/lib/ruby/gems/2.0.0
    LOG_LEVEL=warn

**Comment by Debilski** [comment]
Of course, maybe this is a misunderstanding of what the EMBEDDED_RUBY variable is supposed to do.

**Comment by portertech** [comment]
Sensu installed via the Sensu omnibus packages will always use its embedded ruby. The EMBEDDED_RUBY variable is intended to enable the use of the embedded ruby for Sensu plugins, for checks and handlers. The systemd (and upstart) configs available in /usr/share/sensu just need to be updated by someone :+1:

**Comment by Debilski** [comment]
I’d like to help, but unfortunately I don’t see how to make the systemd script dependent on the environment variable. The upstart solution does not work there (unless an additional wrapper script is added around the ExecStart.

**Comment by emiller42** [comment]
I can corroborate this isn't working as expected.  I've added the following to the service files...
```
[Service]
EnvironmentFile=/etc/default/sensu
...
```
Verified that EMBEDDED_RUBY is appropriately set in the processes environment:
```
# systemctl daemon-reload
# systemctl restart sensu-client
# systemctl status sensu-client
● sensu-client.service - sensu client
   Loaded: loaded (/usr/lib/systemd/system/sensu-client.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2016-01-19 16:29:13 CST; 31s ago
 Main PID: 19517 (sensu-client)
   CGroup: /system.slice/sensu-client.service
           └─19517 /opt/sensu/embedded/bin/ruby /opt/sensu/bin/sensu-client -c /etc/sensu/config.json -d /etc/sensu/conf.d -e /etc/sensu/extensions -l /var/log/sensu/sensu-client.log

# cat /proc/19517/environ
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/binLANG=en_US.UTF-8HOME=/opt/sensuLOGNAME=sensuUSER=sensuEMBEDDED_RUBY=true
```

Looks like plugin instances are spawned with the appropriate environment, but are not using embedded ruby:

```
# ps -f -u sensu
UID        PID  PPID  C STIME TTY          TIME CMD
sensu    19517     1  0 16:29 ?        00:00:00 /opt/sensu/embedded/bin/ruby /opt/sensu/bin/sensu-client -c /etc/sensu/config.json -d /etc/sensu/conf.d -e /etc/sensu/extensions -l /var/log/sensu/sensu
sensu    20225 19517 97 16:35 ?        00:03:12 ruby /etc/sensu/plugins/check-load.rb -w 10,20,30 -c 25,50,75
# cat /proc/20225/environ
EMBEDDED_RUBY=trueSHELL=/bin/falseUSER=sensuPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/binPWD=/LANG=en_US.UTF-8SHLVL=1HOME=/opt/sensuLOGNAME=sensuSENSU_LOADED_TEMPFILE=/tmp/sensu_client_loaded_files_=/etc/sensu/plugins/check-load.rb
```

**Comment by amdprophet** [comment]
This should be fixed in our new build repository as we have implemented a new binstub that the systemd service files wrap.

https://github.com/sensu/sensu-omnibus/blob/master/files/sensu-gem/bin/sensu-service
https://github.com/sensu/sensu-omnibus/blob/master/files/sensu-gem/systemd/sensu-client.service
