### ISSUE TITLE
Windows v0.17.0.beta-1 unable to start sensu-client

### ISSUE THREAD

**Issue by cloakedcode** [sensu/sensu-build#109]
I get this error in the `C:/opt/sensu/bin/sensu-client.err` file when starting the sensu-client. This is from a fresh install of the latest `v0.17.0.beta-1` Windows build.

```
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- 2.0/rubyeventmachine (LoadError)
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.1-x86-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.1-x86-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-logger-1.0.0/lib/sensu/logger/stream.rb:3:in `<top (required)>'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-logger-1.0.0/lib/sensu/logger.rb:1:in `<top (required)>'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.17.0.beta/lib/sensu/daemon.rb:16:in `<top (required)>'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.17.0.beta/lib/sensu/client.rb:1:in `<top (required)>'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.17.0.beta/bin/sensu-client:7:in `<top (required)>'
	from C:/opt/sensu/embedded/bin/sensu-client:23:in `load'
	from C:/opt/sensu/embedded/bin/sensu-client:23:in `<main>'
```

**Comment by portertech** [comment]
Setting up a fresh Windows VM to debug this. Thank you for reporting!

**Comment by rgunst** [comment]
Same problem here on a fresh Windows 2012 R2 VM with v0.17.0.beta-1.

**Comment by portertech** [comment]
@cloakedcode @rgunst I've replaced the defunct beta MSI and flushed the repository CDN, please try again.

**Comment by rgunst** [comment]
I replaced the MSI with the new one.
Still got error 1067 when starting the service. But now without loggin in C:/opt/sensu/bin/sensu-client.err.
When I try to start from the commandline I got this:
*PS C:\Users\Administrator> C:\opt\sensu\embedded\bin\ruby C:\opt\sensu\embedded\bin\sensu-client
{"timestamp":"2015-03-10T08:05:50.827845+0100","level":"fatal","message":"invalid settings"}
{"timestamp":"2015-03-10T08:05:50.890312+0100","level":"fatal","message":"client must be a hash","object":null}
{"timestamp":"2015-03-10T08:05:50.890312+0100","level":"fatal","message":"SENSU NOT RUNNING!"}
PS C:\Users\Administrator>*

**Comment by cloakedcode** [comment]
@rgunst That's not an issue with this build, that's a problem with your configs.

See this issue: https://github.com/sensu/sensu/issues/863

**Comment by rgunst** [comment]
Hmmm,

I just recreated the file c:\etc\sensu\conf.d\client.json with the content:

{
  "client": {
    "name": "denim",
    "address": "172.16.20.68",
    "subscriptions": [ "all" ]
  }
}

Same error.

started with -v and -d options gives:

*PS C:\etc\sensu\conf.d> C:\opt\sensu\embedded\bin\ruby -d -v C:\opt\sensu\embedded\bin\sensu-client
ruby 2.0.0p598 (2014-11-13) [i386-mingw32]
Exception `LoadError' at C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems.rb:1096 - cannot load such file -- rubygems/defau
lts/ruby
C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-2.4.0/lib/sensu/transport.rb:17: warning: shadowing outer
 local variable - klass
Exception `LoadError' at C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/ffi-1.9.6-x86-mingw32/lib/ffi/library.rb:247 - L
oadError
Exception `LoadError' at C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/ffi-1.9.6-x86-mingw32/lib/ffi/library.rb:247 - L
oadError
C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-0.5.0/lib/em-redis/redis_protocol.rb:362: warning: `&' i
nterpreted as argument prefix
C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-logger-1.0.0/lib/sensu/logger.rb:29: warning: instance variable @st
ream not initialized
C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-settings-1.2.0/lib/sensu/settings.rb:38: warning: instance variable
 @loader not initialized
Exception `LoadError' at C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such
file -- oj
Exception `LoadError' at C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:141 - cannot load such
 file -- oj
Exception `LoadError' at C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such
file -- yajl
Exception `LoadError' at C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:141 - cannot load such
 file -- yajl
Exception `LoadError' at C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such
file -- jrjackson
Exception `LoadError' at C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:141 - cannot load such
 file -- jrjackson
Using Ext extension for JSON.
{"timestamp":"2015-03-10T16:24:21.919102+0100","level":"fatal","message":"invalid settings"}
{"timestamp":"2015-03-10T16:24:22.106590+0100","level":"fatal","message":"client must be a hash","object":null}
{"timestamp":"2015-03-10T16:24:22.106590+0100","level":"fatal","message":"SENSU NOT RUNNING!"}
PS C:\etc\sensu\conf.d>*

I will look later today where I went wrong.

**Comment by cloakedcode** [comment]
The client starts normally on windows after an install of the new beta build. Closing.

Thanks @portertech!

**Comment by zonywhoop** [comment]
Just did an upgrade from 0.14.0-1 to 0.17.0-1 (most recent on repos.sensuapp.org) and get the above error.  What beta version currently works?
