### ISSUE TITLE
sensu-0.17.0.beta.1-1

### ISSUE THREAD

**Issue by electricJP** [sensu/sensu-build#112]
Hello,

Testing the latest build on a Win 2012 R2 server. I get the following error:

{"timestamp":"2015-03-16T13:14:22.871809-0400","level":"fatal","message":"invalid settings"}
{"timestamp":"2015-03-16T13:14:22.949945-0400","level":"fatal","message":"client must be a hash","object":null}
{"timestamp":"2015-03-16T13:14:22.949945-0400","level":"fatal","message":"SENSU NOT RUNNING!"}

sensu-0.14.0-1 is working fine with the same client.json:

{
"client": {
"name": "server_fqdn",
"address": "10.136.3.30",
"subscriptions": [ "Windows-servers" ]
}
}

Please note I removed the real FQDN.
Also note I did a version upgrade (not fresh install).

Thank you by advance.

**Comment by zonywhoop** [comment]
Getting the same above error running the MSI available here:
http://repos.sensuapp.org/msi/sensu-0.17.0-1.msi

Running sensu-client from console:
$ /c/opt/sensu/embedded/bin/ruby -d -v /c/opt/sensu/embedded/bin/sensu-client
ruby 2.0.0p598 (2014-11-13) [i386-mingw32]
Exception `LoadError' at c:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems.rb:1096 -
 cannot load such file -- rubygems/defaults/ruby
c:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-2.4.0/lib/sensu/t
ransport.rb:17: warning: shadowing outer local variable - klass
c:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/ffi-1.9.8-x86-mingw32/lib/ffi/enu
m.rb:155: warning: instance variable @native_type not initialized
Exception `LoadError' at c:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/ffi-1.9.
8-x86-mingw32/lib/ffi/library.rb:247 - LoadError
Exception `LoadError' at c:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/ffi-1.9.
8-x86-mingw32/lib/ffi/library.rb:247 - LoadError
c:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-0.6.0/lib/em-red
is/redis_protocol.rb:363: warning: `&' interpreted as argument prefix
c:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-logger-1.0.0/lib/sensu/logg
er.rb:29: warning: instance variable @stream not initialized
c:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-settings-1.3.0/lib/sensu/se
ttings.rb:38: warning: instance variable @loader not initialized
Exception `LoadError' at c:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/
kernel_require.rb:55 - cannot load such file -- oj
Exception `LoadError' at c:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/
kernel_require.rb:141 - cannot load such file -- oj
Exception `LoadError' at c:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/
kernel_require.rb:55 - cannot load such file -- yajl
{"timestamp":"2015-03-26T14:40:39.561689-0500","level":"fatal","message":"invali
d settings"}
{"timestamp":"2015-03-26T14:40:39.670915-0500","level":"fatal","message":"client
 must be a hash","object":null}
{"timestamp":"2015-03-26T14:40:39.670915-0500","level":"fatal","message":"SENSU
NOT RUNNING!"}

**Comment by amdprophet** [comment]
Is this issue still happening with the latest build of Sensu?

**Comment by zonywhoop** [comment]
Not for me.  I believe the issue was fixed after the next release came out.
