### ISSUE TITLE
Add GPG signing keys for RPMs

### ISSUE THREAD

**Issue by ghost** [sensu/sensu-build#117]
We have GPG keys for DEB repos, but the RPMs aren't signed with a GPG key - which is causing concern for us in a corporate env.   I don't want to bother downloading, signing, and uploading to another repo, when 'fpm' does support signing on build.

I'm not sure where to add this in with the funny packager either, so any help with this would be great.

Thanks!

**Comment by neighbous** [comment]
+1 

Same issue here, pls sign the rpms.

**Comment by Bjarke42** [comment]
+1

This issue is critical for using it in a corprate environment.
Also spacewalk is easier with all packages signed

**Comment by rmacduff** [comment]
Agreed. This is especially important since the Sensu packages cannot be downloaded over a secure link (https).

**Comment by redi-walkerd** [comment]
Is there any update on this issue?

**Comment by Daviey** [comment]
Is there any update on this issue?

**Comment by agoddard** [comment]
Hey all, sorry for the radio silence! We're working on this currently and hope to implement it in upcoming builds, we don't have a firm ETA because we're still ironing out some things in the build process, but we'll update again here when we have an ETA.

**Comment by amdprophet** [comment]
I've migrated this issue over to our new build repository. We will be adding RPM signing shortly.

https://github.com/sensu/sensu-omnibus/issues/32
