### ISSUE TITLE
Latest packages ignore Gemfile.lock

### ISSUE THREAD

**Issue by pauloconnor** [sensu/sensu-build#121]
I've updated some of my boxes to 0.19.0. Unfortunately, a lot of gems are running newer versions than are specified in Gemfile.lock, and are breaking various checks as well as sensu-cli

This is the output of gem list from the embedded ruby:
```
 /opt/sensu/embedded/bin $  ./gem list

*** LOCAL GEMS ***

amq-protocol (1.9.2)
amqp (1.5.0)
async_sinatra (1.2.0)
bigdecimal (1.2.0)
childprocess (0.5.3)
daemons (1.2.2)
em-redis-unified (1.0.0)
em-worker (0.0.2)
erubis (2.7.0)
eventmachine (1.0.3)
ffi (1.9.8)
hirb (0.7.1)
io-console (0.4.2)
ipaddress (0.8.0)
json (1.7.7)
minitest (4.3.2)
mixlib-cli (1.5.0)
mixlib-config (2.2.1, 1.1.2)
mixlib-log (1.6.0)
mixlib-shellout (2.1.0)
multi_json (1.11.0)
ohai (6.16.0)
psych (2.0.0)
rack (1.6.1)
rack-protection (1.5.3)
rainbow (2.0.0)
rake (0.9.6)
rdoc (4.0.0)
sensu (0.19.0)
sensu-cli (0.6.3)
sensu-em (2.5.0)
sensu-extension (1.1.2)
sensu-extensions (1.2.0)
sensu-logger (1.0.0)
sensu-plugin (1.1.0)
sensu-settings (1.9.0)
sensu-spawn (1.2.0)
sensu-transport (3.0.0)
sinatra (1.4.6)
systemu (2.6.5, 2.5.2)
test-unit (2.0.0.0)
thin (1.5.0)
tilt (2.0.1)
trollop (2.0)
uuidtools (2.1.4)
yajl-ruby (1.2.1)
```

**Comment by portertech** [comment]
Can you provide an example library dependency issue? The embedded Ruby is ONLY intended to provide the Sensu services (client, server, API) with a working, up-to-date, and consistent Ruby runtime.

**Comment by portertech** [comment]
Sensu uses gem locks to ensure its getting the correct versions, e.g. https://github.com/sensu/sensu/blob/master/lib/sensu/daemon.rb#L5-L11 As users pollute the embedded Ruby.

**Comment by pauloconnor** [comment]
For example, we use sensu-cli https://github.com/agent462/sensu-cli . It expects a version of mixlib-config
```/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'mixlib-config' (= 2.1.0) - did find: [mixlib-config-2.2.1,mixlib-config-1.1.2] (Gem::LoadError)```

It has issues with rainbow once that's fixed

```Could not find 'rainbow' (= 1.99.2)```

**Comment by portertech** [comment]
What in Sensu is requiring mixlib?

**Comment by pauloconnor** [comment]
Sorry, it's sensu-cli that that output is from. I don't know if anything in Sensu requires it. The point of this issue is that embedded ruby in the 0.19.0 sensu package is shipping with different gem versions from the versions listed in the Gemfile.lock which breaks many things, including sensu-plugins and sensu-cli.

**Comment by portertech** [comment]
The Sensu package includes the exact dependencies in the Sensu gemspec, has nothing to do with bundler.

**Comment by portertech** [comment]
It could be the sensu-plugin gem that's pulling in the other dependencies. I recommend adding support to sensu-cli to be able to coexist with other libraries.

**Comment by pauloconnor** [comment]
This was a combination of things.

**Comment by qafro1** [comment]
Please any idea how to resolve this: 
Starting sensu-client/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'sensu' (>= 0) among 19 total gem(s) (Gem::LoadError)
	from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
	from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
	from /opt/sensu/bin/sensu-client:22:in `<main>'
                                                           [FAILED]

**Comment by amdprophet** [comment]
@qafro1 This repository is no longer used for Sensu builds since the release of Sensu 0.27. Please see https://github.com/sensu/sensu-omnibus for the new build repository.
