### ISSUE TITLE
Logrotate is killing Sensu logs daily

### ISSUE THREAD

**Issue by xyntrix** [sensu/sensu-build#123]
It looks like copytruncate was removed from the logrotate.d in Sensu, and pid locating step in logrotate (when using upstart) has never worked.  This breaks logging entirely.   We use the upstart scripts, which doesn't use or need a pid  in /var/run/sensu.  The logrotate scripts expects to use the pid from this path to send USR2 to that sensu daemon PID, but that pid is invalid.

This commit from April is where logrotation broke:

https://github.com/sensu/sensu-build/commit/ab17c9babb4af4f8e09fae7fc61012b867f7b344

The result is that every day that logroate runs, it moves the Sensu log out the way, doesn't sent USR2, and we end up with no more logging for the day.

To fix this there are few options:
- Restore copytruncate (it's fine to use this unless you're running in debug mode.)
- Modify the upstart scripts to track pids in /var/run/sensu/  (Not ideal because: upstart)
- Modify the logrotate scripts to find the Sensu pid through different means, and then send a USR2 to the right process  (Most ideal)

**Comment by dkiser** [comment]
+1

**Comment by xyntrix** [comment]
Also, this issue did not exist in 0.16.  We recently updated from 0.16.x -> 0.19.2, which is why we're just now seeing this issue.   Thanks!

**Comment by xyntrix** [comment]
As a workaround, we're replacing this line in the logrotate:
     kill -USR2 `cat /var/run/sensu/sensu-server.pid 2> /dev/null` 2> /dev/null || true
with:
     kill -USR2 `/sbin/status sensu-server | /bin/egrep -oi "([0-9]+)$" 2> /dev/null` 2> /dev/null || true

Not a good choice for upstream,  since not everyone runs upstart.  We'll keep braining on something more ideal for universal use cases.

**Comment by xyntrix** [comment]
Perhaps having both of these lines in the logrotate would be satisfactory (since both return true).

Alternatively, running this will send a USR2 to all running sensu-N apps no matter what started them.

ps --no-headers -o pid -C sensu-server | awk '{print "kill -USER2 "$1}' | sh

**Comment by heffergm** [comment]
Logging is also broken for those of us using runit, in essentially the same way. I'm not averse to just reverting to copytruncate, but otherwise any USR2 solution should account for the init_type being used.

**Comment by Bjarke42** [comment]
pkill -USR2 sensu-server 
works on centos 7
pkill is a part of procps-ng package.

**Comment by abualy** [comment]
+1
same problem here.
We've recently updated from 0.16 -> 0.20
and didn't notice the problem till we got a disk space issue even if there is no large files in the filesystem, and then noticed **df** command output different to du command output which led us to sensu process still hanging to deleted log files which still counted by the **df** command

**Comment by kcpublic** [comment]
It's now August 2016.  No other resolution yet beyond modifying the logrotate setup manually after the install?

**Comment by kcpublic** [comment]
Or another option as well is to add configuration capabilities in the sensu configurations to control max file size and rotation of logs directly so logrotate is not needed to be set up.

Currently, you can only specify logging level and directory location for the files.

**Comment by cwjohnston** [comment]
Hello @xyntrix @dkiser @heffergm @abualy and @kcpublic 

Thank you for raising this issue; I apologize that it has gone unresolved for so long. Given how Sensu has developed since this issue was first opened, I believe it is the case that we won't be trying to fix this issue as it relates to upstart specifically. 

We are currently working to migrate Sensu's build and release process away from the tools in this repo to a toolchain using Chef's Omnibus (see #184). As part of this process we are planning to drop support for upstart and runit to focus on sysv and systemd as the officially supported service managers (see https://github.com/sensu/sensu-omnibus/issues/34) .
