### ISSUE TITLE
Upgrade to latest ruby gems

### ISSUE THREAD

**Issue by runningman84** [sensu/sensu-build#128]
Right now sensu has some old ruby gems installed (2.0.x). Please upgrade to the latest (2.4.2) release.

**Comment by portertech** [comment]
Will test 2.4.x.

**Comment by runningman84** [comment]
any news here?

**Comment by amdprophet** [comment]
@runningman84 I believe we're running a `gem update --system` with each build. Is this still an issue?

**Comment by runningman84** [comment]
not it is fixed:
```
$ /opt/sensu/embedded/bin/gem --version
2.6.6
```
