### ISSUE TITLE
Fedora 22 systemd service file support

### ISSUE THREAD

**Issue by nkts** [sensu/sensu-build#132]

**Comment by cwjohnston** [comment]
We are currently working to migrate Sensu's build and release process away from the tools in this repo to a toolchain using Chef's Omnibus (see #184). 

As part of this process we are planning to drop support for upstart and runit to focus on sysv and systemd as the officially supported service managers (see https://github.com/sensu/sensu-omnibus/issues/34).

I believe these changes will not be necessary for running omnibus builds on Centos 7 and other platforms with systemd as the init system. I've added this issue to the 0.27 milestone to reflect that it is superseded by the switch to omnibus builds which will be used to generate Sensu 0.27 packages.
