### ISSUE TITLE
Sensu RPMs missing gems after build

### ISSUE THREAD

**Issue by sureshsubramaniam** [sensu/sensu-build#138]
i am using rvm with the ruby 2015-04-13 patchlevel 645, and when building the rpm on a RHEL 6.x, the build completes successfully, but the rpm is missing the required "sensu-server", sensu-client and most of all the gems in the package
The gem environment looks as below
RubyGems Environment:
  - RUBYGEMS VERSION: 2.0.14
  - RUBY VERSION: 2.0.0 (2015-04-13 patchlevel 645) [x86_64-linux]
  - INSTALLATION DIRECTORY: /opt/sensu/embedded/lib/ruby/gems/2.0.0
  - RUBY EXECUTABLE: /opt/sensu/embedded/bin/ruby
  - EXECUTABLE DIRECTORY: /opt/sensu/embedded/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /opt/sensu/embedded/lib/ruby/gems/2.0.0
     - /home/sensu/.gem/ruby/2.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/

If i try to change the gem locations, the build.sh removes all the files under /opt/sensu so during the runtime of the build ruby cannot be located
Any alternate options (ideas/tweakings to the sensu-build or my environment) to have the sensu built on RHEL would be much appreciated

**Comment by amdprophet** [comment]
Hi @sureshsubramaniam. This repository will no longer be used for Sensu builds. Please see https://github.com/sensu/sensu-omnibus for our new build tools.
