### ISSUE TITLE
epoch needs to be an option passed to bunchr for fpm

### ISSUE THREAD

**Issue by emoby** [sensu/sensu-build#141]
I'm not sure if I should post this here in sensu-build or in bunchr, so I'll post it here since Joe Miller is on this project too.

The sensu rpm releases have a epoch value of "1", which impacts the way that rpm see's the version.  I built a sensu-0.20.6-1 rpm, and yet it would not be upgraded from 0.19, as I was returned this message.

```
# rpm -Uvh sensu-0.20.6-1.x86_64.rpm
Preparing packages for installation...
package sensu-1:0.19.2-1.x86_64 (which is newer than sensu-0.20.6-1.x86_64) is already installed
```

Can epoch be an option that is added to the Rakefile, or an environment var-- since it is used for package naming and parsing?

I solved by problem by inserting a value in the fpm command, yet it could be a instance var:
/lib/bunchr/packages.rb
...
#127           --iteration #{iteration}                              \
#128           --epoch 1                                                \

Thanks for a great package!

**Comment by amdprophet** [comment]
@emoby thank you for bringing this to our attention. We have a new repository that we'll be using for Sensu builds from now on (https://github.com/sensu/sensu-omnibus). We will likely add epoch support to the new build system but we're hoping to drop the use of it by Sensu 1.0.

I've created an issue in our new repository to track any discussion we have around the problem: https://github.com/sensu/sensu-omnibus/issues/35
