### ISSUE TITLE
Support newer versions of Microsoft .Net framework

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-build#149]
* Our [current implementation winsw](https://github.com/sensu/sensu-build/blob/master/recipes/winsw.rake) requires .Net 3.5 to run sensu-client as a service
* "Starting with NT Version 6.2 (Windows 8/2012) .NET 3 is an on demand feature. Meaning that you need either to use the installing media or a custom windows image to enable the feature." This makes it very hard to do reasonable automated testing of Sensu installation in other projects (e.g. sensu/sensu-chef)
* Newer versions of winsw support alternate .Net runtimes (see https://github.com/kohsuke/winsw#net-runtime-40)
* If we upgrade our implementation of winsw we can more easily support a wider number of Windows targets

**Comment by agoddard** [comment]
:+1:

**Comment by portertech** [comment]
https://github.com/sensu/sensu-build/pull/150 fixed!
