### ISSUE TITLE
packages missing readline support

### ISSUE THREAD

**Issue by eheydrick** [sensu/sensu-build#151]
Ruby readline support has been missing in builds since sensu 0.20.0. Readline support is useful when you're trying things in irb. Also, `sensu-plugins-wordpress` requires wpscan which requires readline support. The chef-omnibus builds include readline support using libedit. Would be nice to see it in sensu.

**Comment by amdprophet** [comment]
Tracking this issue in our new Omnibus repository here: https://github.com/sensu/sensu-omnibus/issues/47
