### ISSUE TITLE
Wrong ruby version in sensu-install with 0.23

### ISSUE THREAD

**Issue by runningman84** [sensu/sensu-build#153]
Since sensu 0.23 uses ruby 2.3, you should also use it here:
https://github.com/sensu/sensu-build/blob/master/sensu_configs/bin/sensu-install

**Comment by runningman84** [comment]
https://github.com/sensu/sensu-build/pull/154

**Comment by GhostLyrics** [comment]
Fix is in 2cb4422ba6186875fd1986e38dabe794f8c6a89d.

**Comment by portertech** [comment]
Closing because it was fixed in the 0.23.1 build :+1:
