### ISSUE TITLE
Investigate issues with RPM packages on CentOS 5.10 

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-build#155]
See: https://github.com/sensu/sensu/issues/1152

**Comment by calebhailey** [comment]
We've also seen this in a few other places besides the linked Sensu issue... we've successfully resolved this by building a one-off package in a different build environment, but we haven't yet identified and implemented the actual remedy.

**Comment by amdprophet** [comment]
This should be fixed with the release of 0.27 which is built in our new build repository (https://github.com/sensu/sensu-omnibus).
