### ISSUE TITLE
Windows MSI installer creates path with double backslash

### ISSUE THREAD

**Issue by AirCombat** [sensu/sensu-build#156]
```
C:\>echo %PATH%
C:\Program Files (x86)\Python35-32\Scripts\;C:\Program Files (x86)\Python35-32\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Program Files\Amazon\AWSCLI\;C:\Program Files\Git\cmd;C:\opt\sensu\\bin
```

`
C:\opt\sensu\\bin`

calebhailey:
https://github.com/sensu/sensu-build/blob/0bd2a4334a5425997d4b98ea43f0e160b675e7e4/assets/msi/files/Sensu.wxs#L42

**Comment by amdprophet** [comment]
This is fixed in our new build repository by the following commit: https://github.com/sensu/sensu-omnibus/commit/93ded1109f26b48ee0d3d5d1e4a6d2769b37fb1a. The fix will be included in the upcoming 0.27 release.
