### ISSUE TITLE
Windows sensu-client.xml uses Linux EOLs

### ISSUE THREAD

**Issue by AirCombat** [sensu/sensu-build#158]
The sensu-client.xml (and likely other files) use Unix style LF line endings not windows CRLF, which causes the file to be incorrectly formatted when viewed with a non LF aware text editor such as notepad.

This may be due to an incorrect configuration of git

**Comment by portertech** [comment]
@wbrodie interesting, the xml configuration file was likely created on a nix machine. We'll try to get this into the 0.24 build :+1:

**Comment by amdprophet** [comment]
This has been fixed by https://github.com/sensu/sensu-omnibus/commit/8e236d3acbe687aeba9cbbead054dc6405da0996
