### ISSUE TITLE
Config Directories not included in default sensu-client.xml (Windows)

### ISSUE THREAD

**Issue by AirCombat** [sensu/sensu-build#159]
The documentation initially refers to C:\opt\sensu\config.json and C:\opt\sensu\conf.d\ as locations to store config files and then later in the document instructs users to change the service wrapper to include these.

This seems unnecessary. It's nice that we have the option to change it if we want but we shouldn't have to put those arguments in from the start, they should be there already.

I also think sensu-client should be installed as a service by the MSI, but then there's a larger argument as to why it is necessary to have one huge monolithic installer that includes both the server and the client.

**Comment by portertech** [comment]
@wbrodie I too think the documented suggested paths should just become the defaults :+1: 

As for the monolithic installer point, the difference would only be a few KB, all of the dependencies are shared. It is actually possible to run every component on Windows, but it's not recommended.

**Comment by amdprophet** [comment]
This is fixed in our new build repository with the following commit: https://github.com/sensu/sensu-omnibus/commit/232b1849a4b24525dba76954464aef793b1105d2. The fix will be included with the upcoming 0.27 release.
