### ISSUE TITLE
Windows package ships with EOL Ruby

### ISSUE THREAD

**Issue by eheydrick** [sensu/sensu-build#161]
The Windows package ships with Ruby 2.0.0, which is EOL and no longer receiving security updates. It should be updated to the latest Ruby release.

**Comment by cwjohnston** [comment]
We're going to address this in the [new omnibus builds](https://github.com/sensu/sensu-build/issues/184); we expect Sensu 0.27 Windows packages will ship with Ruby 2.3.0.
