### ISSUE TITLE
Deregister events generated by init script should specify interval and refresh 

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-build#162]
As mentioned here https://github.com/sensu/sensu-build/pull/148#issuecomment-218370362, folks are having difficulty with reliability of deregistration. Suggested fix:

> add 'interval: 1, refresh: 1' to deregister event json here: https://github.com/sensu/sensu-build/pull/148/files#diff-32a7b82f0e4d5b8e858da79847107666R202 so that it will never filtered out by 'filter_repeated'.

**Comment by cwjohnston** [comment]
If the changes in https://github.com/sensu/sensu/issues/1309 are accepted, this issue can be closed as we'll subsequently remove the deregistration behavior from the init scripts.

**Comment by amdprophet** [comment]
Deregistration functionality was removed from the init scripts and moved into Sensu Core.
