### ISSUE TITLE
Wrong arch for .deb on PowerPC

### ISSUE THREAD

**Issue by travbrack** [sensu/sensu-build#168]
Hi there

I built a sensu deb on my powerpc system (Debian Wheezy) using your instructions, however I'm getting the following when I try to install:

```
dpkg: error processing sensu_0.25.4-1_ppc.deb (--install):
 package architecture (ppc) does not match system (powerpc)
Errors were encountered while proce
```

It works great with --force-architecture.  Uname -a shows:
```
Linux foo.bar 3.2.68-6 #3.2.71-1 SMP Mon Mar 7 16:57:12 PST 2016 ppc powerpc GNU/Linux
```

so apparently the script is using 'ppc' instead of 'powerpc' which Debian expects.  I think this might be an upstream issue in bunchr, but I thought I'd try here first.

**Comment by amdprophet** [comment]
Hi @travbrack,

Thank you for reporting this issue. We aren't currently building deb packages for the powerpc platform - I'll be putting this on our roadmap. We cannot give any timelines as to when this feature may be complete but we can prioritize issues for Sensu Enterprise customers.

#monitoringlove

**Comment by amdprophet** [comment]
@travbrack I apologize - I misread the initial issue description. I just accepted a PR the https://github.com/joemiller/bunchr repository that should fix this issue. Please clone & install bunchr from master and then try to rerun the Sensu build process again.

**Comment by amdprophet** [comment]
@travbrack I just uploaded a powerpc deb package release of 0.25.7 to our Sensu Core repository. Feel free to give it a try - otherwise the solution in my previous message should get your build moving along nicely.

**Comment by travbrack** [comment]
Thank you so much!  The package installed perfectly.  Having a powerpc deb in the official repo saves me so much hassle, this is incredible.  @amdprophet will you guys be building powerpc going forward, or should I plan on building my own packages still?

**Comment by amdprophet** [comment]
@travbrack Glad to hear it's working! I'll be building them with each new release but I don't have many cycles to dedicate to fixing PPC builds in the event that they break.
