### ISSUE TITLE
Export plugin path recursively

### ISSUE THREAD

**Issue by kaushiksriram100** [sensu/sensu-build#169]
Trying to see if it makes sense for sensu user to export the plugin & handler paths recursively. If we want to organize plugins based in several directories inside /etc/sensu/plugins? 

https://github.com/sensu/sensu-build/blob/master/sensu_configs/init.d/sensu-service#L21

**Comment by amdprophet** [comment]
Hi @kaushiksriram100,

Adding recursive directories within `/etc/sensu/plugins` to PATH will increase the chance of unexpected behaviour in cases where two or more plugins have the same name but exist in two different subdirectories.

As a side note, subdirectories in `/etc/sensu/plugins` can be used so long as your check definitions use the full path to the plugin.

#monitoringlove
