### ISSUE TITLE
sensu-service cant read config

### ISSUE THREAD

**Issue by Kosm0** [sensu/sensu-build#170]
bash-4.2# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
bash-4.2#

ps -aux | grep sensu-server 
root 6528 0.5 1.0 199508 19164 ? Sl 19:13 0:00 /opt/sensu/embedded/bin/ruby /opt/sensu/bin/sensu-server -b -c /etc/sensu/config.json -d /etc/sensu/conf.d -e /etc/sensu/extensions -p /var/run/sensu/sensu-server.pid -l /var/log/sensu/sensu-server.log -L info
root 6585 0.0 0.0 112644 976 pts/1 S+ 19:14 0:00 grep --color=auto sensu-server
-bash-4.2# /opt/sensu/bin/sensu-server -P
{"timestamp":"2016-07-16T19:14:55.906248+0300","level":"warn","message":"outputting compiled configuration and exiting"}
{
"sensu":{
"spawn":{
"limit":12
}
},
"transport":{
"name":"rabbitmq",
"reconnect_on_error":true
},
"checks":{},
"filters":{},
"mutators":{},
"handlers":{}
}

manual start is OK ! (i see sensu connect in RabbitMQ)
-bash-4.2# /opt/sensu/bin/sensu-server -c /etc/sensu/config.json
{"timestamp":"2016-07-16T19:15:18.203854+0300","level":"warn","message":"loading config file","file":"/etc/sensu/config.json"}
{"timestamp":"2016-07-16T19:15:18.238715+0300","level":"warn","message":"loaded extension","type":"mutator","name":"ruby_hash","description":"returns ruby hash event data"}
{"timestamp":"2016-07-16T19:15:18.238885+0300","level":"warn","message":"loaded extension","type":"mutator","name":"json","description":"returns JSON formatted event data"}
{"timestamp":"2016-07-16T19:15:18.239007+0300","level":"warn","message":"loaded extension","type":"mutator","name":"only_check_output","description":"returns check output"}
{"timestamp":"2016-07-16T19:15:18.239122+0300","level":"warn","message":"loaded extension","type":"handler","name":"debug","description":"returns raw event data"}
{"timestamp":"2016-07-16T19:15:18.239504+0300","level":"info","message":"configuring sensu spawn","settings":{"limit":12}}
{"timestamp":"2016-07-16T19:15:20.403217+0300","level":"info","message":"i am now the leader"}
{"timestamp":"2016-07-16T19:15:50.404731+0300","level":"info","message":"determining stale clients"}
{"timestamp":"2016-07-16T19:15:50.405134+0300","level":"info","message":"determining stale check results"}
{"timestamp":"2016-07-16T19:15:50.412190+0300","level":"info","message":"processing event","event":{"client":{"name":"demo-computer","address":"10.8.16.8","subscriptions":["windows","windowschecks"],"safemode":false,"timestamp":1468587

**Comment by cwjohnston** [comment]
Hi @Kosm0, sorry it's been quite a while since you opened this issue, but have you looked at the permissions on the file? By default the sysv init scripts run the daemons as user "sensu" and your config files may not have the correct permissions.

**Comment by Kosm0** [comment]
Thank's, it was realy. I desire  this problem long time ago. 
Thank you so much, you a extrasens, because you investigate this problem with my little message =)

**Comment by cwjohnston** [comment]
💯
