### ISSUE TITLE
Validate Config error handling

### ISSUE THREAD

**Issue by mnguyen1289** [sensu/sensu-build#173]
The validate_config function of the init script does not seem to handle empty JSON files gracefully.

The bug:
  - validate_config function spews out a ton of ruby errors if the sensu-service is restarted with a empty JSON file in /etc/sensu.conf.d (Error is listed at the bottom)

To replicate:
  - Add a empty JSON file (completely empty - no text) to /etc/sensu/conf.d and restart the sensu
service 
  
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings/loader.rb:307:in `deep_merge': undefined method `each' for nil:NilClass (NoMethodError)
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings/loader.rb:110:in `load_file'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings/loader.rb:143:in `block in load_directory'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings/loader.rb:142:in `each'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings/loader.rb:142:in `load_directory'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings.rb:24:in `block in load'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings.rb:23:in `each'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings.rb:23:in `load'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings.rb:42:in `get'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.5/lib/sensu/daemon.rb:131:in `load_settings'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.5/lib/sensu/daemon.rb:51:in `initialize'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.5/lib/sensu/client/process.rb:29:in `initialize'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.5/lib/sensu/client/process.rb:17:in `new'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.5/lib/sensu/client/process.rb:17:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.5/exe/sensu-client:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-client:22:in `load'
        from /opt/sensu/bin/sensu-client:22:in `<main>'

It would be nice to have validate_config catch the error and spit out something descriptive like "Unable to parse <file name>" instead of the ruby errors above.

**Comment by ankitg1989** [comment]
Whats the current fix for this?

**Comment by cwjohnston** [comment]
@ankitg1989 I've opened issue https://github.com/sensu/sensu-settings/issues/49 to track this.
