### ISSUE TITLE
FreeBSD rc scripts should be properly formatted

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-build#175]
As per @inferiorhumanorgans (https://github.com/sensu/sensu/issues/1429):

The way they are structured now, the services do not come up at boot. Documentation is available here:

https://www.freebsd.org/doc/en/articles/rc-scripting/

https://www.freebsd.org/doc/en/books/porters-handbook/rc-scripts.html

**Comment by amdprophet** [comment]
@inferiorhumanorgans is this also happening with the sensu-client service?

**Comment by inferiorhumanorgans** [comment]
Probably (I haven't rebooted the only thing I'm running sensu-client on).  Any init scripts without the proper keywords will be passed over at boot time.

**Comment by inferiorhumanorgans** [comment]
Additionally the it would be nice if the log level were configurable from rc.conf (ex: it should come in via sensu_foo_args).  More importantly the default should probably be warn not info, as info will spam the logs incessantly.

**Comment by amdprophet** [comment]
Thank you for all of the feedback!

The various Sensu services will now start on boot (after `LOGIN`)  if enabled in `rc.conf`. This will be available in the upcoming 0.27 release. See https://github.com/sensu/sensu-omnibus/commit/e01eea07cd79d1f521eafe44786162e6da289a16 for more information.

We've created a new service binstub in `/opt/sensu/bin/sensu-service` which will be used across most, if not all, of the platforms we support. Due to the way the binstub currently works it is not yet possible to use `sensu_foo_args` to override LOG_LEVEL. As an alternative, you may set `LOG_LEVEL=warn` in `/usr/local/etc/default/sensu`.

Changing the default log level is something that will affect all platforms; please open a separate issue in the `sensu/sensu-omnibus` project so that it can be discussed.

#monitoringlove
