### ISSUE TITLE
FreeBSD packages are corrupt and cause pkg(8) to segfault

### ISSUE THREAD

**Issue by inferiorhumanorgans** [sensu/sensu-build#177]
Per https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=212022

`seems like the package was made via fpm somehow, and the manifest is missing lots of entries. anyway pkg should not segfault but yell at the missing fields, I will fix it (via yelling)`

**Comment by amdprophet** [comment]
I'm hoping to have this solved with our new Omnibus build tools (https://github.com/sensu/sensu-omnibus). I am currently implementing the pkgng spec in Omnibus here: https://github.com/sensu/omnibus/pull/2

**Comment by amdprophet** [comment]
I managed to solve this in the new Omnibus packages. The fix will be included with the upcoming Sensu 0.27 release.
